### ISSUE TITLE
(User Research)  As a team member, I want a better understanding of how the Facebook Chatbot tool is currently implemented and what opportunities for chatbots might exist. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/10x-qualitative-data#26]
## 10x Qualitative Data User story 
(User Research)  As a team member, I want a better understanding of how the Facebook Chatbot tool is currently implemented and what opportunities for chatbots might exist. 

## Acceptance criteria
- [x] Talk to Content Team about the Chatbot tool (contact Ashlea)
- [x] Consider also directing users to Contact Center (might be worth a content editing look, related to issue #27)
- [x] Decide whether chatbot tool can be implemented as part of the solution to provide users more opportunities for real-time, customizable information

**Comment by OpenGlobe** [comment]
We're scheduled for tomorrow here.

**Comment by kategarklavs** [comment]
@OpenGlobe Not sure if you all already had an agenda/list of questions, but I jotted down a few questions in this doc:

https://docs.google.com/document/d/1ugFuUX4zZszRmNOY81Hg3nePpCFlhvHd0ZXxER7HYOo/edit?usp=sharing

**Comment by OpenGlobe** [comment]
Combined notes doc is [here](https://docs.google.com/document/d/1sQTWKeFGAyeA6VU5hi2R-60e7JuLdbxgMQYyIelY1E0/edit#)!  

Since it looks like we're waiting on approvals prior to implementation, I suggest we consider implementation of the chatbot as something to revisit

**Comment by DK1999** [comment]
If this is closed, should it move to the Done column?
