### ISSUE TITLE
As a team member, I want to determine if utilizing Qualtrics will negatively impact our ability to complete our goals.

### ISSUE THREAD

**Issue by amoose** [18F/10x-qualitative-data#6]
- [x] Recreate sample surveys in Qualtrics
- [x] Populate with real and fake survey responses
- [x] Summarize reporting capabilities in comparison to current process and output
- [x] Landscape of licensing, other government users, existing support at GSA
- [x] List of other gov’t agencies that we can identify using on-line surveys of various types

Subtask: Investigate an for surveying mobile users.
Amos will determine if Qualtrics and Site Intercept are capable of capturing valuable survey responses from mobile users. Can we offer some kind of incentive?

Follow up with Lauren...
**Update:** underway already, about halfway done - needs to be written up

**Comment by OpenGlobe** [comment]
David spent some time working on styling and invitations to get to a level of confidence with the product, in order to understand if it could fulfill our needs.

**Comment by DK1999** [comment]
I think Qualtrics will work. From my standpoint, we can close this ticket.
