### ISSUE TITLE
As a team member, I want to determine if more structured questions generate actionable information

### ISSUE THREAD

**Issue by amoose** [18F/10x-qualitative-data#7]
## User story 
As a **team member**
I want **to gain actionable information from survey responses**
so that **the user's experience is enhanced** with better content, navigation, etc. 
  
## Acceptance criteria
- [x] Build sample surveys with more structured questions (same questions, less text fields)
- [x] Populate surveys with sample data
- [x]  Review with the Analytics Team
- [x] Generate reports from the new surveys 
- [x] Determine if reporting generates actionable information for team members

**Comment by OpenGlobe** [comment]
Still need some things to address, delayed somewhat since we're not immediately rewriting all the questions.

**Comment by kategarklavs** [comment]
@OpenGlobe I just responded to David's feedback on the questions 👍 Would you all like me to join any work sessions/meetings next week to discuss? Or should I take another stab at writing questions?

**Comment by amoose** [comment]
The consensus is that _better_ questions would improve the actionable outcomes. We can close this issue now in favor of https://github.com/18F/10x-qualitative-data/issues/27

**Comment by DK1999** [comment]
I don't think that most of the acceptance criteria checkboxes should be marked on this one? I think we are certain that we want to come up with surveys that are more productive.  However, we haven't done stuff like coming up with a draft survey, or at least that I know of.  I think that should be a deliverable for this project. It will take a long time afterwards for the new survey to get built in Qualtrics, it gets PRA approval, it gets put in the field for a while, the data gets assessed. We may then change it. A significant change will require a new approval. Then the HSM needs to get updated to reflect the new survey. All reporting will need to get updated.  So, that's a long term thing. Half a year or so.

**Comment by DK1999** [comment]
I have a first pass at new sitewide survey questions to discuss with folks / introduce into a process to develop new questions. https://docs.google.com/document/d/1zswmJsuIpKS8voJrRruajK6xxJAHEXHJ_E8lYPQdo0o/edit
