### ISSUE TITLE
As a team member, I want to identify a more reliable way to survey mobile users (POP-UP)

### ISSUE THREAD

**Issue by OpenGlobe** [18F/10x-qualitative-data#9]
## User story 
As a team member, I want to identify a more appropriate way to offer mobile users the sitewide pop-up survey that allows those who accept to complete their off-site task before doing the survey.
  
## Acceptance criteria
- [x] Amos will determine if Qualtrics and Site Intercept are capable of capturing valuable survey responses from mobile users.
- [x] Reach out to Lauren A. to identify options
- [x] Identify options, if any, for offering survey incentives

**Comment by OpenGlobe** [comment]
We're going to keep this in the icebox - Qualtrics can do what we need (for now).

**Comment by OpenGlobe** [comment]
David to update / edit based on current issues (tabbing issues, etc.)

**Comment by amoose** [comment]
Remaining Section 508 issues here: https://github.com/18F/10x-qualitative-data/issues/28

**Comment by DK1999** [comment]
I have some ideas for doing a pop up on mobile that requires setting a browser cookie and multiple modals.
1) Pop up modal, sized for mobile, invites participant.
2) Yes to help performs these actions: (1) closes pop up modal (2) sets session/browser cookie (3) opens a new creative above the header.
3) The new header creative has a link to start the survey in a third modal, that is a full screen modal. Instructions in the header creative say that when they are done with their task, browse back to usa.gov (if necessary) and click the link to start.
4) The browser cookie is used to fire the header creative on every usa.gov page until the browser has been closed, which deletes the cookie
5) Also, a possible touch would be a small modal that fires (only once) when they exit the site that reminds them to return to the site before the browser app is closed to participate in the survey.
